layout_spectrum: 0.9617021
typography_spectrum: 0.2151869
color:
  lightness: 0.3978723
  brandStrength: 0.9479988
  saturation: 0.3617021
  rhythmicContrast: 0.776589
  brandColors:
    - '#4287D0'
    - '#DF5D54'
    - '#FFFFFF'
    - '#778830'
    - '#1F2754'
name: 'VanGerena '
